DROP TABLE IF EXISTS CUSTOMER_MAIL_INFO;
CREATE TABLE CUSTOMER_MAIL_INFO
(
    ID          VARCHAR(32)  NOT NULL COMMENT 'ID',
    EMAIL       VARCHAR(128) NOT NULL COMMENT '邮箱地址',
    ENABLED     CHAR(1)      NOT NULL COMMENT '是否启用Y-是 N-否',
    EXPIRE_DATE INT          NOT NULL COMMENT '到期时间yyyyMMdd,使用29991231代表永久有效',
    CREATE_TIME DATETIME     NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME     NOT NULL COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '客户邮件信息表';

DROP TABLE IF EXISTS NEWS;
CREATE TABLE NEWS
(
    ID          VARCHAR(32)   NOT NULL COMMENT 'ID',
    TITLE       VARCHAR(255)  NOT NULL COMMENT '标题',
    DETAIL      VARCHAR(1000) NOT NULL COMMENT '描述',
    URL         VARCHAR(1000) NOT NULL COMMENT '链接',
    RANK        INT           NOT NULL COMMENT '热搜排名',
    HOT_SCORE   INT           NOT NULL COMMENT '热度值',
    BATCH_ID    VARCHAR(32)   NOT NULL COMMENT '批次ID',
    CHANNEL     CHAR(3)       NOT NULL COMMENT '新闻渠道EnumNewsChannelType',
    CREATE_TIME DATETIME      NOT NULL COMMENT '创建时间',
    UPDATE_TIME DATETIME      NOT NULL COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '新闻表';
CREATE INDEX IDX_BATCH_ID ON NEWS(BATCH_ID);

DROP TABLE IF EXISTS NEWS_CHANNEL;
CREATE TABLE NEWS_CHANNEL
(
    ID           INT         NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    CHANNEL_CODE CHAR(3)     NOT NULL COMMENT '渠道编号EnumNewsChannelType',
    CHANNEL_NAME VARCHAR(32) NOT NULL COMMENT '渠道名称',
    ENABLED      CHAR(1)     NOT NULL COMMENT '渠道是否启用Y-启用N-不启用',
    CREATE_TIME  DATETIME    NOT NULL COMMENT '创建时间',
    UPDATE_TIME  DATETIME    NOT NULL COMMENT '更新时间',
    PRIMARY KEY (ID)
) COMMENT = '渠道配置表';

DROP TABLE IF EXISTS NEWS_BATCH_RECORD;
CREATE TABLE NEWS_BATCH_RECORD
(
    BATCH_ID     VARCHAR(32) NOT NULL COMMENT 'ID',
    HAS_SENT     CHAR(1)     NOT NULL COMMENT '新闻是否已发送给客户Y-是N-否',
    CREATE_TIME  DATETIME    NOT NULL COMMENT '创建时间',
    UPDATE_TIME  DATETIME    NOT NULL COMMENT '更新时间',
    PRIMARY KEY (BATCH_ID)
) COMMENT = '新闻批次表';

-- 初始化一个收件人
INSERT INTO CUSTOMER_MAIL_INFO (ID, EMAIL, ENABLED, EXPIRE_DATE, CREATE_TIME, UPDATE_TIME) VALUES ('1', 'xxxxxx@163.com', 'Y', 20991231, '2024-01-04 13:02:15', '2024-01-04 13:02:18');
-- 初始化渠道编号百度热搜
INSERT INTO NEWS_CHANNEL (ID, CHANNEL_CODE, CHANNEL_NAME, ENABLED, CREATE_TIME, UPDATE_TIME) VALUES (1, '001', '百度热搜', 'Y', '2024-01-04 13:05:40', '2024-01-04 13:05:42');


